-- ========================================
-- Issue #42: RBAC Phase 1 — app_role enum + public.user_roles
-- ========================================
--
-- Supabase 公式 RBAC ガイドが示す canonical pattern に揃えるための
-- 別テーブル方式へのリファクタの第 1 段階。本マイグレーションは **追加のみ** で、
-- 既存の `profiles.role` は引き続き存続する（Phase 2 でアプリ層を切替えてから drop）。
--
-- アプリ層 (`src/actions/index.ts` の `requireAdmin`) は Phase 1 完了時点では
-- 引き続き `profiles.role` を読み続ける。`/admin/*` の挙動は不変。
--
-- 公式: https://supabase.com/docs/guides/database/postgres/custom-claims-and-role-based-access-control-rbac
--
-- 関連 Issue:
--   - 本 Issue: #42 (Phase 1)
--   - Phase 2 (#43): is_admin() security definer 関数 + アプリ切替 + profiles.role drop
--   - Phase 3 (#44): Custom Access Token Hook で user_role claim を JWT embed → DB 引き 0 回化

-- ----------------------------------------
-- 1. app_role enum
-- ----------------------------------------
-- 教科書版は ('admin', 'moderator') だが、本テンプレは既存の
-- profiles.role に合わせて ('admin', 'member') を採用する。
-- 将来 'moderator' を追加するときは `alter type public.app_role add value 'moderator';`。
create type public.app_role as enum ('admin', 'member');

comment on type public.app_role is
  'RBAC: ユーザーのロール列挙。Phase 1 で profiles.role を user_roles に移行するための受け皿。';

-- ----------------------------------------
-- 2. user_roles テーブル
-- ----------------------------------------
create table public.user_roles (
  id      bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role    public.app_role not null,
  unique  (user_id, role)
);

comment on table public.user_roles is
  'RBAC: ユーザのロール割り当て。authenticated は自分の行のみ select 可、書き換えは service_role のみ。';

-- ----------------------------------------
-- 3. RLS: 自分の role のみ select 可
-- ----------------------------------------
-- 「自分は admin か」をクライアント / admin UI が判定するために必要な最小権限。
-- 他人の role 行は見えない（権限保有者の網羅は admin Action 経由 + service_role で行う）。
alter table public.user_roles enable row level security;

create policy "Users can view own role"
on public.user_roles for select
to authenticated
using ((select auth.uid()) = user_id);

-- ----------------------------------------
-- 4. 権限剥奪 + service_role への明示 grant
-- ----------------------------------------
-- 20260427002055_fix_profiles_role_privilege_escalation.sql と同じパターン。
-- Supabase の default privileges は authenticated に表全体の DML を grant してくる
-- ことがあり、column-level revoke は no-op になりうる。table-level revoke で確実に
-- 剥奪し、必要な権限（select）だけを再付与する。
revoke all on public.user_roles from authenticated;
grant select on public.user_roles to authenticated;

-- service_role への明示 grant: admin.updateUserRole 等が user_roles を CRUD するため。
grant all on public.user_roles to service_role;

-- ----------------------------------------
-- 5. RLS column index
-- ----------------------------------------
-- 公式: "Add indexes on any columns used within the Policies which are not already
--        indexed (or primary keys)."
-- user_id は FK で auto-index されないため明示的に貼る。
create index user_roles_user_id_idx on public.user_roles (user_id);

-- ----------------------------------------
-- 6. 既存 profiles.role を user_roles に data migration
-- ----------------------------------------
-- profiles.role は Phase 2 完了まで残置する（アプリ層がまだ読んでいるため）。
-- on conflict do nothing: 万一既に行があっても idempotent に migrate する。
insert into public.user_roles (user_id, role)
select user_id, role::public.app_role
  from public.profiles
 where role is not null
on conflict (user_id, role) do nothing;

-- ----------------------------------------
-- 7. handle_new_user() を user_roles INSERT 込みに更新
-- ----------------------------------------
-- 既存 (20260506010103_harden_handle_new_user_search_path.sql) との差分:
--   - profiles INSERT に加えて user_roles INSERT (default 'member') を追加
--   - search_path = '' は維持（Issue #41）
--
-- create or replace なので既存 trigger (on_auth_user_created) はそのまま。
-- profiles と user_roles は同一 transaction で挿入されるため、片方だけ作られる
-- 中途半端な状態にはならない。
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', ''));

  -- 新規ユーザはデフォルトで 'member' role を持つ。
  -- 'admin' への昇格は admin.updateUserRole が service_role 経由で別途行う。
  insert into public.user_roles (user_id, role)
  values (new.id, 'member'::public.app_role);

  return new;
end;
$$;
